### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by gelzinyte**
Modify/add a higher-level "Basic use" description, move README content to the docs and clean up docstrings.

### CODE REVIEW

**Comment by gelzinyte** [comment]
@bernstei do you have anything to add or change? (Feel free to just edit the docs)

**Comment by bernstei** [comment]
I see some of the cleanup, but not the README content move that's mentioned in the 1st comment.  Am I just missing something, or is that not pushed yet?

**Comment by gelzinyte** [comment]
Should be there now!

**Comment by bernstei** [comment]
Thanks.  Do you know how to set up the github.io autodoc stuff, so I don't have to build them manually?

**Comment by gelzinyte** [comment]
I was going to copy QUIP's if you meant to publishing equivalently to https://libatoms.github.io/QUIP/ ?

**Comment by bernstei** [comment]
Yes - I'm just trying to get out of having to build them myself (although I don't know how it'd work with branches in the ExPyRe repo - I guess for now we can just have this PR's branch do it, and switch over to the main branch doing it once it's merged).

**Comment by gelzinyte** [comment]
Ok let me work that out

**Comment by gelzinyte** [comment]
ok - documentation is now built to `gh-pages` branch on pull requests to `main`. I've also added an action to run tests, a la workflow.

**Comment by gelzinyte** [comment]
@bernstei the newly introduced tests are failing, but I would like to merge this so we can put some documentation online and open an issue/PR to fix the tests, if that sounds good?

**Comment by bernstei** [comment]
Fine by me.  Do we even understand why those tests are failing now?

**Comment by bernstei** [comment]
I know why these tests are failing now - I'm more wondering why it wasn't a problem before. Nothing having to do with remote runs can run on github CI because there's no queuing system.  I assumed we just had those turned off previously.

**Pull request merged**
